image: Visual Studio 2015

version: "{build}"
clone_folder: c:\go-work\src\gotable

environment:
  GOPATH: c:\go-work

install:
  - cinst make -v -y
  - cinst wkhtmltopdf -v -y -d
  - gem install sass
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - echo %PATH%
  - go version
  - go env
  - go get -t -v ./...

build_script:
  - make
  - go build -o buildOutput\gotable -i .

artifacts:
  - path: buildOutput/gotable
    name: gotable

test_script:
  - make test