image: Visual Studio 2015

version: "{build}"
clone_folder: c:\go-work\src\gotable

environment:
  GOPATH: c:\go-work

install:
  # make installation
  - cinst make -v -y
  # wkhtmltopdf installation
  - cinst wkhtmltopdf -v -y -d
  # sass installation
  - gem install sass
  - go get -u github.com/golang/lint/golint
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - echo %PATH%
  - go version
  - go env
  # build the dependency
  - make

build_script:
  - go build -o buildOutput\gotable -i .

artifacts:
  - path: buildOutput/gotable
    name: gotable

test_script:
  - make test

on_success:
  - make clean