image: Visual Studio 2015

version: "{build}"
clone_folder: c:\go-work\src\gotable

environment:
  GOPATH: c:\go-work
  WKHTMLTOPDFPATH: c:\wkhtmltopdf

install:
  - cinst make -v -y
  - cinst wkhtmltopdf -v -y
  - gem install sass
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%WKHTMLTOPDFPATH%;%PATH%
  - echo %PATH%
  - go version
  - go env
  - go get -t -v ./...

before_build:
  - cmd: ECHO this is batch
  - ps: Write-Host "This is PowerShell"

build_script:
  - go build -o buildOutput\gotable -i .
  - make

artifacts:
  - path: buildOutput/gotable
    name: gotable binary

test_script:
  - make test