version: "{build}"
clone_folder: c:\gotable

environment:
  GOPATH: c:\gopath

install:
  - cinst wkhtmltopdf
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get -t -v ./...

before_build:
  - cmd: ECHO this is batch
  - ps: Write-Host "This is PowerShell"

build_script:
  - go build -o buildOutput\gotable -i .

artifacts:
  - path: buildOutput/gotable
    name: gotable binary