# image: Visual Studio 2015

version: "{build}"
clone_folder: c:\go-work\src\gotable

environment:
  matrix:
    - TARGET: msvc2013-win32
    - TARGET: msvc2015-win64
  GOPATH: c:\go-work
  WKHTMLTOPDFPATH: c:\wkhtmltopdf

install:
  - cinst make -v -y
  - cinst wkhtmltopdf -v -y
  # - cinst wget -v -y
  # - wget -O c:\wkhtmltopdf\wkhtmltopdf.exe http://download.gna.org/wkhtmltopdf/0.12/0.12.4/wkhtmltox-0.12.4_mingw-w64-cross-win64.exe
  # - c:\wkhtmltopdf\wkhtmltopdf.exe
  - gem install sass
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%WKHTMLTOPDFPATH%;%PATH%
  - echo %PATH%
  - go version
  - go env
  - go get -t -v ./...

# before_build:
#   - cmd: ECHO this is batch
#   - ps: Write-Host "This is PowerShell"

build_script:
  - go build -o buildOutput\gotable -i .
  - make

artifacts:
  - path: buildOutput/gotable
    name: gotable binary

test_script:
  - make test